import { OrderDetails } from "@/types/order";

export const mockOrderData: OrderDetails = {
  orderId: "ORD-2024-78542",
  orderDate: "2024-01-15T10:30:00Z",
  estimatedDelivery: "2024-01-20T18:00:00Z",
  status: "out_for_delivery",
  trackingNumber: "PK123456789",
  carrier: "TCS Express",
  carrierUrl: "https://www.tcsexpress.com/track",
  items: [
    {
      id: "item-1",
      name: "Premium Gold Embroidered Shawl",
      image: "/api/placeholder/120/120",
      quantity: 1,
      price: 8500,
      variant: "Maroon / Large",
      sku: "SHW-GLD-001",
    },
    {
      id: "item-2",
      name: "Handcrafted Leather Wallet",
      image: "/api/placeholder/120/120",
      quantity: 2,
      price: 3200,
      variant: "Brown",
      sku: "WLT-LTH-002",
    },
  ],
  shippingAddress: {
    name: "Ahmed Hassan",
    phone: "+92 300 1234567",
    email: "ahmed.hassan@email.com",
    street: "House 123, Street 45, F-10/3",
    city: "Islamabad",
    state: "Islamabad Capital Territory",
    postalCode: "44000",
    country: "Pakistan",
  },
  billingAddress: {
    name: "Ahmed Hassan",
    phone: "+92 300 1234567",
    email: "ahmed.hassan@email.com",
    street: "House 123, Street 45, F-10/3",
    city: "Islamabad",
    state: "Islamabad Capital Territory",
    postalCode: "44000",
    country: "Pakistan",
  },
  subtotal: 14900,
  shippingCost: 0,
  tax: 745,
  discount: 1000,
  total: 14645,
  paymentMethod: "Credit Card (****4582)",
  trackingHistory: [
    {
      id: "evt-1",
      status: "pending",
      title: "Order Placed",
      description: "Your order has been successfully placed",
      timestamp: "2024-01-15T10:30:00Z",
      isCompleted: true,
      isCurrent: false,
    },
    {
      id: "evt-2",
      status: "confirmed",
      title: "Order Confirmed",
      description: "Payment verified and order confirmed",
      timestamp: "2024-01-15T10:35:00Z",
      isCompleted: true,
      isCurrent: false,
    },
    {
      id: "evt-3",
      status: "processing",
      title: "Processing",
      description: "Your order is being prepared for shipment",
      location: "Lahore Warehouse",
      timestamp: "2024-01-16T09:00:00Z",
      isCompleted: true,
      isCurrent: false,
    },
    {
      id: "evt-4",
      status: "shipped",
      title: "Shipped",
      description: "Package picked up by TCS Express",
      location: "Lahore Hub",
      timestamp: "2024-01-17T14:20:00Z",
      isCompleted: true,
      isCurrent: false,
    },
    {
      id: "evt-5",
      status: "out_for_delivery",
      title: "Out for Delivery",
      description: "Your package is on its way to you",
      location: "Islamabad Distribution Center",
      timestamp: "2024-01-19T08:45:00Z",
      isCompleted: false,
      isCurrent: true,
    },
    {
      id: "evt-6",
      status: "delivered",
      title: "Delivered",
      description: "Package will be delivered to you",
      timestamp: "",
      isCompleted: false,
      isCurrent: false,
    },
  ],
};
