import { Category, Product } from "@/types/product";
import {
  Droplets,
  Flame,
  Gift,
  Leaf,
  Moon,
  Sparkles,
  Sun,
  Wind,
} from "lucide-react";

// export const allProducts: Product[] = [
//   {
//     Id: 1,
//     name: "Herbal Hair Growth Oil",
//     description:
//       "Nourishing blend of natural oils to promote healthy hair growth and reduce hair fall.",
//     price: "Rs. 1,299",
//     image:
//       "https://images.unsplash.com/photo-1669281393403-e1f3248dce2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwaGFpciUyMG9pbCUyMGJvdHRsZXxlbnwxfHx8fDE3NjI3OTA4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//     category: "Hair Care",
//   },
//   {
//     Id: 2,
//     name: "Natural Glow Face Cream",
//     description:
//       "Illuminate your skin with this hydrating cream enriched with herbal extracts.",
//     price: "Rs. 1,499",
//     image:
//       "https://images.unsplash.com/photo-1615205597144-5c7c885291d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBza2luY2FyZSUyMGNyZWFtJTIwamFyfGVufDF8fHx8MTc2Mjc5MDgwOHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//     category: "Skin Care",
//   },
//   {
//     Id: 3,
//     name: "Herbal Face Serum",
//     description:
//       "Concentrated botanical formula for deep nourishment and radiant skin.",
//     price: "Rs. 1,799",
//     image:
//       "https://images.unsplash.com/photo-1671493234884-b1611bcf3e69?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBza2luY2FyZSUyMGJvdHRsZXMlMjBuYXR1cmFsfGVufDF8fHx8MTc2Mjc5MDgwN3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//     category: "Skin Care",
//   },
//   // {
//   //   Id: 4,
//   //   name: "Scalp Treatment Oil",
//   //   description:
//   //     "Therapeutic herbal blend to soothe and revitalize your scalp naturally.",
//   //   price: "Rs. 1,399",
//   //   image:
//   //     "https://images.unsplash.com/photo-1669281393403-e1f3248dce2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwaGFpciUyMG9pbCUyMGJvdHRsZXxlbnwxfHx8fDE3NjI3OTA4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//   //   category: "Hair Care",
//   // },
//   // {
//   //   id: 5,
//   //   name: "Rose & Sandalwood Face Pack",
//   //   description:
//   //     "Traditional herbal face pack for brightening and deep cleansing.",
//   //   price: "Rs. 899",
//   //   image:
//   //     "https://images.unsplash.com/photo-1615205597144-5c7c885291d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBza2luY2FyZSUyMGNyZWFtJTIwamFyfGVufDF8fHx8MTc2Mjc5MDgwOHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//   //   category: "Skin Care",
//   // },
//   // {
//   //   id: 6,
//   //   name: "Anti-Dandruff Hair Oil",
//   //   description: "Herbal formula to eliminate dandruff and soothe itchy scalp.",
//   //   price: "Rs. 1,199",
//   //   image:
//   //     "https://images.unsplash.com/photo-1669281393403-e1f3248dce2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwaGFpciUyMG9pbCUyMGJvdHRsZXxlbnwxfHx8fDE3NjI3OTA4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//   //   category: "Hair Care",
//   // },
//   // {
//   //   id: 7,
//   //   name: "Turmeric & Neem Face Wash",
//   //   description: "Gentle herbal cleanser for clear, glowing skin.",
//   //   price: "Rs. 799",
//   //   image:
//   //     "https://images.unsplash.com/photo-1671493234884-b1611bcf3e69?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBza2luY2FyZSUyMGJvdHRsZXMlMjBuYXR1cmFsfGVufDF8fHx8MTc2Mjc5MDgwN3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//   //   category: "Skin Care",
//   // },
//   // {
//   //   id: 8,
//   //   name: "Deep Conditioning Hair Mask",
//   //   description: "Rich herbal treatment for soft, shiny, and manageable hair.",
//   //   price: "Rs. 1,599",
//   //   image:
//   //     "https://images.unsplash.com/photo-1615205597144-5c7c885291d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBza2luY2FyZSUyMGNyZWFtJTIwamFyfGVufDF8fHx8MTc2Mjc5MDgwOHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
//   //   category: "Hair Care",
//   // },
// ];

export const categories: Category[] = [
  {
    id: "facial-oils",
    name: "Facial Oils",
    slug: "facial-oils",
    icon: Droplets,
    count: 24,
  },
  {
    id: "hair-oils",
    name: "Hair Oils",
    slug: "hair-oils",
    icon: Wind,
    count: 18,
  },
  {
    id: "body-oils",
    name: "Body Oils",
    slug: "body-oils",
    icon: Sun,
    count: 15,
  },
  {
    id: "essential-oils",
    name: "Essential Oils",
    slug: "essential-oils",
    icon: Leaf,
    count: 32,
  },
  {
    id: "herbal-serums",
    name: "Herbal Serums",
    slug: "herbal-serums",
    icon: Sparkles,
    count: 20,
  },
  {
    id: "natural-creams",
    name: "Natural Creams",
    slug: "natural-creams",
    icon: Moon,
    count: 16,
  },
  {
    id: "herbal-masks",
    name: "Herbal Masks",
    slug: "herbal-masks",
    icon: Flame,
    count: 12,
  },
  {
    id: "gift-sets",
    name: "Gift Sets",
    slug: "gift-sets",
    icon: Gift,
    count: 8,
  },
];

export const sortOptions = [
  { id: "featured", name: "Featured" },
  { id: "newest", name: "Newest Arrivals" },
  { id: "bestselling", name: "Bestselling" },
  { id: "price-low", name: "Price: Low to High" },
  { id: "price-high", name: "Price: High to Low" },
  { id: "rating", name: "Highest Rated" },
  { id: "discount", name: "Biggest Discount" },
];

// Product images - using picsum for reliable placeholders
export const productImages = [
  "https://picsum.photos/seed/oil1/400/400",
  "https://picsum.photos/seed/oil2/400/400",
  "https://picsum.photos/seed/oil3/400/400",
  "https://picsum.photos/seed/oil4/400/400",
  "https://picsum.photos/seed/oil5/400/400",
  "https://picsum.photos/seed/oil6/400/400",
  "https://picsum.photos/seed/oil7/400/400",
  "https://picsum.photos/seed/oil8/400/400",
  "https://picsum.photos/seed/oil9/400/400",
  "https://picsum.photos/seed/oil10/400/400",
  "https://picsum.photos/seed/oil11/400/400",
  "https://picsum.photos/seed/oil12/400/400",
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Moroccan Argan Oil - Pure & Cold Pressed",
    slug: "moroccan-argan-oil-pure",
    description:
      "100% pure, cold-pressed Moroccan Argan oil for face, hair, and body.",
    shortDescription:
      "Multi-purpose beauty oil for radiant skin and silky hair",
    images: [productImages[0], productImages[1]],
    price: 2850,
    originalPrice: 3500,
    discount: 19,
    category: "facial-oils",
    tags: ["bestseller", "organic"],
    ingredients: ["argan", "vitamin-e"],
    skinType: ["dry", "normal", "mature"],
    concerns: ["aging", "dryness", "dullness"],
    rating: 4.8,
    reviewCount: 324,
    inStock: true,
    stockCount: 45,
    isNew: false,
    isBestseller: true,
    isFeatured: true,
    isOrganic: true,
    volume: "30ml",
    sku: "ARG-001",
    benefits: ["Deep hydration", "Anti-aging", "Reduces wrinkles"],
    createdAt: "2024-01-01",
  },
  {
    id: "prod-2",
    name: "Rosehip Seed Oil - Organic Cold Pressed",
    slug: "rosehip-seed-oil-organic",
    description:
      "Organic rosehip seed oil rich in vitamins A and C for skin regeneration.",
    shortDescription: "Natural retinol alternative for youthful, glowing skin",
    images: [productImages[1], productImages[2]],
    price: 2200,
    originalPrice: 2800,
    discount: 21,
    category: "facial-oils",
    tags: ["organic", "new"],
    ingredients: ["rosehip", "vitamin-e", "retinol"],
    skinType: ["combination", "mature", "normal"],
    concerns: ["aging", "dark-spots", "dullness"],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    stockCount: 32,
    isNew: true,
    isBestseller: false,
    isFeatured: true,
    isOrganic: true,
    volume: "30ml",
    sku: "RSH-002",
    benefits: ["Brightening", "Scar reduction", "Even skin tone"],
    createdAt: "2024-01-10",
  },
  {
    id: "prod-3",
    name: "Bhringraj Hair Growth Oil",
    slug: "bhringraj-hair-growth-oil",
    description:
      "Traditional Ayurvedic hair oil with Bhringraj for hair growth and strength.",
    shortDescription:
      "Ayurvedic formula to reduce hair fall and promote growth",
    images: [productImages[2], productImages[3]],
    price: 1650,
    originalPrice: 2000,
    discount: 18,
    category: "hair-oils",
    tags: ["ayurvedic", "bestseller"],
    ingredients: ["coconut", "neem"],
    skinType: ["normal"],
    concerns: ["hair-fall", "dandruff"],
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    stockCount: 78,
    isBestseller: true,
    isFeatured: false,
    isOrganic: true,
    volume: "100ml",
    sku: "BHR-003",
    benefits: ["Reduces hair fall", "Promotes growth", "Strengthens roots"],
    createdAt: "2024-01-05",
  },
  {
    id: "prod-4",
    name: "Tea Tree Purifying Face Oil",
    slug: "tea-tree-purifying-face-oil",
    description:
      "Clarifying face oil with tea tree and neem for acne-prone skin.",
    shortDescription: "Clear skin solution for acne and blemishes",
    images: [productImages[3], productImages[4]],
    price: 1850,
    originalPrice: 2200,
    discount: 16,
    category: "facial-oils",
    tags: ["acne-control"],
    ingredients: ["tea-tree", "neem", "jojoba"],
    skinType: ["oily", "combination"],
    concerns: ["acne", "pores"],
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    stockCount: 56,
    isNew: false,
    isFeatured: false,
    volume: "25ml",
    sku: "TTR-004",
    benefits: ["Fights acne", "Controls oil", "Minimizes pores"],
    createdAt: "2024-01-08",
  },
  {
    id: "prod-5",
    name: "Lavender Essential Oil - Therapeutic Grade",
    slug: "lavender-essential-oil",
    description: "Pure lavender essential oil for aromatherapy and skincare.",
    shortDescription: "Calming aromatherapy oil for relaxation and skin care",
    images: [productImages[4], productImages[5]],
    price: 950,
    originalPrice: 1200,
    discount: 21,
    category: "essential-oils",
    tags: ["aromatherapy", "organic"],
    ingredients: ["lavender"],
    skinType: ["sensitive", "normal"],
    concerns: ["redness", "dryness"],
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    stockCount: 120,
    isBestseller: true,
    isFeatured: true,
    isOrganic: true,
    volume: "15ml",
    sku: "LAV-005",
    benefits: ["Calming", "Stress relief", "Better sleep"],
    createdAt: "2024-01-02",
  },
  {
    id: "prod-6",
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description:
      "Powerful vitamin C serum with natural extracts for brightening.",
    shortDescription: "Radiance-boosting serum for glowing, even-toned skin",
    images: [productImages[5], productImages[6]],
    price: 3200,
    originalPrice: 4000,
    discount: 20,
    category: "herbal-serums",
    tags: ["brightening", "new"],
    ingredients: ["hyaluronic", "aloe-vera"],
    skinType: ["normal", "combination", "oily"],
    concerns: ["dark-spots", "dullness"],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    stockCount: 40,
    isNew: true,
    isFeatured: false,
    volume: "30ml",
    sku: "VTC-006",
    benefits: ["Brightens skin", "Fades dark spots", "Boosts collagen"],
    createdAt: "2024-01-12",
  },
  {
    id: "prod-7",
    name: "Kumkumadi Tailam - Radiance Oil",
    slug: "kumkumadi-tailam-radiance",
    description: "Ancient Ayurvedic formula for radiant, flawless skin.",
    shortDescription: "Luxurious Ayurvedic oil for a golden glow",
    images: [productImages[6], productImages[7]],
    price: 4500,
    originalPrice: 5500,
    discount: 18,
    category: "facial-oils",
    tags: ["ayurvedic", "luxury", "bestseller"],
    ingredients: ["turmeric"],
    skinType: ["dry", "normal", "mature"],
    concerns: ["aging", "dark-spots", "dullness"],
    rating: 4.9,
    reviewCount: 412,
    inStock: true,
    stockCount: 25,
    isBestseller: true,
    isFeatured: false,
    volume: "25ml",
    sku: "KUM-007",
    benefits: ["Radiant glow", "Even skin tone", "Anti-aging"],
    createdAt: "2024-01-03",
  },
  {
    id: "prod-8",
    name: "Almond & Coconut Body Oil",
    slug: "almond-coconut-body-oil",
    description: "Nourishing body oil blend for silky smooth skin.",
    shortDescription: "Deep moisturizing body oil for soft, supple skin",
    images: [productImages[7], productImages[8]],
    price: 1450,
    originalPrice: 1800,
    discount: 19,
    category: "body-oils",
    tags: ["moisturizing"],
    ingredients: ["coconut", "vitamin-e"],
    skinType: ["dry", "normal"],
    concerns: ["dryness"],
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
    stockCount: 65,
    isFeatured: false,
    volume: "200ml",
    sku: "ACB-008",
    benefits: ["Deep hydration", "Soft skin", "Natural glow"],
    createdAt: "2024-01-06",
  },
  {
    id: "prod-9",
    name: "Turmeric & Neem Face Mask",
    slug: "turmeric-neem-face-mask",
    description: "Purifying face mask with turmeric and neem for clear skin.",
    shortDescription: "Deep cleansing mask for clear, healthy skin",
    images: [productImages[8], productImages[9]],
    price: 1250,
    originalPrice: 1500,
    discount: 17,
    category: "herbal-masks",
    tags: ["purifying"],
    ingredients: ["turmeric", "neem", "aloe-vera"],
    skinType: ["oily", "combination"],
    concerns: ["acne", "pores", "dullness"],
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    stockCount: 48,
    isFeatured: false,
    volume: "100g",
    sku: "TNM-009",
    benefits: ["Deep cleansing", "Fights acne", "Brightening"],
    createdAt: "2024-01-09",
  },
  {
    id: "prod-10",
    name: "Jojoba Oil - Golden Organic",
    slug: "jojoba-oil-golden-organic",
    description: "Pure golden jojoba oil that mimics skin's natural sebum.",
    shortDescription: "Lightweight oil for balanced, healthy skin",
    images: [productImages[9], productImages[10]],
    price: 1950,
    originalPrice: 2400,
    discount: 19,
    category: "facial-oils",
    tags: ["organic", "lightweight"],
    ingredients: ["jojoba", "vitamin-e"],
    skinType: ["oily", "combination", "sensitive"],
    concerns: ["acne", "pores", "redness"],
    rating: 4.7,
    reviewCount: 298,
    inStock: true,
    stockCount: 52,
    isOrganic: true,
    isFeatured: false,
    volume: "50ml",
    sku: "JOJ-010",
    benefits: ["Balances oil", "Non-comedogenic", "Soothing"],
    createdAt: "2024-01-04",
  },
  {
    id: "prod-11",
    name: "Anti-Aging Night Serum",
    slug: "anti-aging-night-serum",
    description:
      "Intensive night repair serum with natural retinol alternatives.",
    shortDescription: "Overnight repair for youthful, firm skin",
    images: [productImages[10], productImages[11]],
    price: 3800,
    originalPrice: 4800,
    discount: 21,
    category: "herbal-serums",
    tags: ["anti-aging", "night-care"],
    ingredients: ["rosehip", "retinol", "hyaluronic"],
    skinType: ["mature", "dry", "normal"],
    concerns: ["aging", "dryness"],
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    stockCount: 30,
    isNew: true,
    isFeatured: false,
    volume: "30ml",
    sku: "ANS-011",
    benefits: ["Reduces wrinkles", "Firms skin", "Overnight repair"],
    createdAt: "2024-01-11",
  },
  {
    id: "prod-12",
    name: "Complete Skincare Gift Set",
    slug: "complete-skincare-gift-set",
    description: "Luxurious gift set with our bestselling oils and serums.",
    shortDescription: "Perfect gift for natural beauty lovers",
    images: [productImages[11], productImages[0]],
    price: 8500,
    originalPrice: 12000,
    discount: 29,
    category: "gift-sets",
    tags: ["gift", "luxury", "bestseller"],
    ingredients: ["argan", "rosehip", "lavender", "vitamin-e"],
    skinType: ["normal", "dry", "combination"],
    concerns: ["aging", "dryness", "dullness"],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    stockCount: 15,
    isBestseller: true,
    isFeatured: false,
    sku: "GFT-012",
    benefits: ["Complete routine", "Premium quality", "Beautiful packaging"],
    createdAt: "2024-01-07",
  },
];
