import "./globals.css";
import { Inter, Noto_Nastaliq_Urdu } from "next/font/google";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});
const notoUrdu = Noto_Nastaliq_Urdu({
  subsets: ["arabic"], // Urdu uses Arabic script subset
  weight: ["400"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} ${notoUrdu.className}`}>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
